version: '3.9'
name: 'webgpt'
services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    container_name: backend
    command:
      python manage.py runsslserver --certificate ./ssl/summericy.pem --key
      ./ssl/summericy.key 0.0.0.0:8000
    volumes:
      - './backend/:/backend/'
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    container_name: post_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'

volumes:
  postgres_data:
